import Logo from "./components/Logo";
import Nav from "./components/Nav";

export const metadata = {
  title: "Beach Club",

  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Nav />
        </header>
        <main>{children}</main>
        <footer>&copy; Beach Resort 2025</footer>
      </body>
    </html>
  );
}
